### ISSUE TITLE
Spells/Equipment/Combat/Features & Traits

### ISSUE THREAD

**Issue by DMsGuild201** [KingCosmic/BardsBallad#11]
"Search..." 
might be confusing for laypersons - and not realize that search is only for that feature's implemented /choose set. (presumably - as search doesn't work currently)

suggestion make 

"Search...."
Into "Search your <spells/eqeuipment/etc>"
or search all of it, and pop a "+" on a result to add it to that list

**Comment by KingCosmic** [comment]
yea search works on the add popups, I do need to add the filters to them but it shouldn't be hard to do.

**Comment by KingCosmic** [comment]
made the placeholder changes
