### ISSUE TITLE
Action /Edit notification consistency

### ISSUE THREAD

**Issue by DMsGuild201** [KingCosmic/BardsBallad#12]
Mousing over the vales should indicate they are editable - info tab, if you mouse over a field the field's background changes color; denoting editable. 

Example: Equipment (Money Values);  Skills (Armor/Weapon/Tools Proficiencies)

ALSO:
clicking on Skills (Armor/Weapon/Tools Proficiencies) after doing do, the first edit erases the pre-existing text.
Ideally it would be a pick list of available proficiencies; with an additional field for "add your own"
Skills; 
Suggestion; pop a mouse over tool text letting the user know blue = half proficiency; Green = proficient; Yellow = expertise.

Side thought.
You might want to allow the specific number be editable directly for the proficiency.

(its not raw, but... people/dms etc - will have devices/magic items/spells that modify a specific skill)

**Comment by KingCosmic** [comment]
I've tried doing the tooltip, but I failed to get it to change when the user clicked to show the updated data, but I can try again
