### ISSUE TITLE
Spell / Equipment/Combat/Features & Traits

### ISSUE THREAD

**Issue by DMsGuild201** [KingCosmic/BardsBallad#13]
Suggestion

When you add <element>

Confirm should be in a green box to be consistent with the add/save theme for Usability.

**Comment by DMsGuild201** [comment]
(I'd also avoid making poped up details editable by default, 
The popup for when its in inventory with the delete (back in this case) and edit (which I'd suggest be green as well) would suffice.

**Comment by DMsGuild201** [comment]
The edit popup should scroll down and the description text be fully presented for editing, the scroll shouldn't be limited to description / (and for spells "higher levels")

also, editing higher levels removes all text - and fields when in edit should be consistent in their visual prompt and performance to the rest - ideally like the info tab.

Fields that are impacted.

For Spells
Duration, Casting time, Range, Name, Description Higher levels

Equipment
Name; range; damage, value, quantity(See note); long range, attack bonus; additional damage; damage two handed; weight; properties(see note); Description

Feat 
(likely would have that)

**Comment by KingCosmic** [comment]
I'm working on all these, the hardest one is the description scrolling as for some magical reason text areas aren't able to expand to show their full content, and I'm working on a workaround, Thanks for the feedback

**Comment by KingCosmic** [comment]
fixed everything except the description scroll, that's being a tough one

**Comment by KingCosmic** [comment]
description now scales to show all content
