### ISSUE TITLE
Equipment

### ISSUE THREAD

**Issue by DMsGuild201** [KingCosmic/BardsBallad#14]
If over 1 of such in equipment.

Allow for reduction of quantity on the popup window without needed to access full edit of the item.

Reasoning; lots of consumable materials; health kit; arrows; potions of healing,etc

**Comment by KingCosmic** [comment]
some of these examples (arrows) I was planning to have as resources when I add that functionality, but for stuff like potions and health kits it does make sense, thanks for the feedback and working on it rn
