### ISSUE TITLE
equipment

### ISSUE THREAD

**Issue by DMsGuild201** [KingCosmic/BardsBallad#15]
Duplication check.
When adding duplicated materials; increment quantity and remove duplicate entires so only one entry remains with the combined quantity.

Action
Go into inventory; add Acid (vial) three times. with different values

Suggested action;
When entering a duplicate entry either error trap and respond, or modify the existing entry with updated quantity.

**Comment by KingCosmic** [comment]
I agree this should be a feature, though it's a big hard to implement because a user can make custom items out of already existing ones. I could increase quantity based on item name
