### ISSUE TITLE
Toggle certain UI

### ISSUE THREAD

**Issue by K1ll3rM** [KingCosmic/BardsBallad#24]
Ability to toggle mainly the spells tab and the XP bar for characters that don't need it.

**Comment by KingCosmic** [comment]
nice suggestion, but removing some stuff like a tab could screw with the design as a whole, unsure if I want to do that.

**Comment by K1ll3rM** [comment]
![image](https://user-images.githubusercontent.com/24224847/59594160-a3bc7380-90f3-11e9-8445-9da7c55de010.png)
Removing 2 tabs still looks fine to me, only spells should need to have a toggle though, combat would come back after it actually has some content

**Comment by KingCosmic** [comment]
🤔

**Comment by KingCosmic** [comment]
will add it into the settings for a character.
