### ISSUE TITLE
Empty state placeholder

### ISSUE THREAD

**Issue by K1ll3rM** [KingCosmic/BardsBallad#25]
Empty state placeholders like Discord:
![image](https://user-images.githubusercontent.com/24224847/59495252-3d371b80-8e8f-11e9-80b1-98f672fb7816.png)
And facebook:
![image](https://user-images.githubusercontent.com/24224847/59495269-488a4700-8e8f-11e9-8d71-44ff7ff19e48.png)

Like facebook, you can have the relevant button in the placeholder.

**Comment by KingCosmic** [comment]
created one for characters, don't really think one is needed for lists like spells and equipment. Can put it to a vote in the server if you want
