### ISSUE TITLE
Modal changes

### ISSUE THREAD

**Issue by K1ll3rM** [KingCosmic/BardsBallad#29]
- The buttons back and confirm in the item and spell modals should be buttons instead of just text.
- Normalize the font size of different options (dropdown texts are larger than other text)
- Add a checkbox option instead of using a dropdown with true/false
- Increase the height of the edit item modal to the same as that of the "new item" modal.
- Increase description height in some places (like new spell), having to scroll for them doesn't matter as much as actually being able to see a significant part of the description

**Comment by KingCosmic** [comment]
most of these changes are already in issues (buttons, normalize, description height). as for a checkbox instead of the dropdown, it looks wonky, and feels off having one there I tried that before doing the dropdown.
also for the modal height, just fixed that, I accidently coded something weird
