### ISSUE TITLE
Make blue temp health bar visible over or under normal health

### ISSUE THREAD

**Issue by K1ll3rM** [KingCosmic/BardsBallad#4]
![image](https://user-images.githubusercontent.com/24224847/59418346-2a5a1380-8dc9-11e9-987a-eea59a23829b.png)
or
![image](https://user-images.githubusercontent.com/24224847/59418410-4a89d280-8dc9-11e9-843e-2480e34759ed.png)

**Comment by KingCosmic** [comment]
changed some health calculations, it now changes the max so calculations show a new max 
![image](https://user-images.githubusercontent.com/24766991/59470022-209dd380-8dfc-11e9-978b-70527d549277.png)
