### ISSUE TITLE
rework styling

### ISSUE THREAD

**Issue by KingCosmic** [KingCosmic/BardsBallad#50]
instead of styled-components I'd like to have everything be styled by css

**Comment by KingCosmic** [comment]
also in our lists instead of index math we can just do something like

```css
tr:nth-child(even) {background: #CCC}
tr:nth-child(odd) {background: #FFF}```
(curtesy of AKingHasNoName)

**Comment by K1ll3rM** [comment]
Personally I really like using Bootstrap 5 with SCSS. If you use SCSS version of Bootstrap it's really easy to work with colors.

**Comment by KingCosmic** [comment]
The plan is to mix css with utility library tailwind css
