### ISSUE TITLE
Right stat block improvements

### ISSUE THREAD

**Issue by K1ll3rM** [KingCosmic/BardsBallad#6]
### Inconsistent font size ###
Looks a bit weird at some screen sizes.
![image](https://user-images.githubusercontent.com/24224847/59419063-6fcb1080-8dca-11e9-9f21-07de61071d6e.png)

### Change Armor Class to AC ###
It's a bit unneeded to have the full name there, this way it would line up with speed and initiative. Maybe add a hover tool tip to clarify it for new player but everyone should know what AC means.

### Remove save buttons ###
Just allow editing the value directly just like the descriptions on the info tab.

### More info on bigger screens ###
There's still a lot of empty space above it that could be filled with info if the screen is big enough.

### Use the area instead modals ###
Whenever you're editing something like health which will need more room than it normally takes, the entire area could be used instead of using a modal and switch back after closing the health editing.

**Comment by K1ll3rM** [comment]
PS. We need a name for these stats to refer to them more easily

**Comment by KingCosmic** [comment]
Armor Class changed to AC, font-size issues fixed, save buttons are staying atm. feel free to make a issue just for no save buttons and some suggestions on the info I can show on bigger screens. call then General Stats
